version: '3.4'

services:
  api:
    image: braido/braidorental-api
    ports:
        - 80:8000
        - 443:4430
        
  web:
    image: braido/braidorental-web
    ports:
        - 3000:3000

  db:
    image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
    environment:
        SA_PASSWORD: "<YourStrong@Passw0rd>"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433