version: '3.4'

services:  
  db:
    image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
    environment:
        SA_PASSWORD: "<YourStrong@Passw0rd>"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
      
  api:
    image: braidorentalapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 32700:80
      - 32743:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        
  web:
    image: braidorentalweb
    ports:
        - 3000:80

